### ISSUE TITLE
renderCaptcha doesn't work

### ISSUE THREAD

**Issue by soshimee** [dimdenGD/OWOP.js_v2#13]
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'ws')
    at Object.dataHandler (eval at _callee$ (app.js:5743:78), <anonymous>:468:84)
    at ws.onmessage (eval at _callee$ (app.js:5743:78), <anonymous>:543:68)
```
(Line 468)
```
                                        } else if (options.renderCaptcha) this.net.ws.send(OWOP.options.serverAddress[0].proto.misc.tokenVerification + (await renderCaptcha()));
```
`net` is undefined.

**Comment by soshimee** [comment]
Probably should be `OJS.net` instead of `this.net`?
