### ISSUE TITLE
how to connect proxy?

### ISSUE THREAD

**Issue by MapleHackersoff** [dimdenGD/OWOP.js_v2#9]
how to connect HTTPS proxy?

**Comment by dimdenGD** [comment]
Use https://www.npmjs.com/package/https-proxy-agent and pass it in `agent` option

**Comment by MapleHackersoff** [comment]
```
var options = url.parse(proxy);
var agent = new HttpsProxyAgent(options);
var socket = new WebSocket(endpoint, { agent: agent });

const OJS = require("owop-js");
const Client = new OJS.Client({
    reconnect: true,
    controller: true
});

Client.on("join", () => {
    Client.chat.send("Hello, OWOP from OJS!");
});
```
like this?

**Comment by dimdenGD** [comment]
something like
```js
let options = url.parse(proxy);
let agent = new HttpsProxyAgent(options);

const OJS = require("owop-js");
const Client = new OJS.Client({
    reconnect: true,
    controller: true,
    agent
});

Client.on("join", () => {
    Client.chat.send("Hello, OWOP from OJS!");
});
```

**Comment by MapleHackersoff** [comment]
error:
```error
D:\owop bot\index.js:4
let agent = new HttpsProxyAgent(options);
            ^

ReferenceError: HttpsProxyAgent is not defined
    at Object.<anonymous> (D:\owop bot\index.js:4:13)
[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:928:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m

D:\owop bot>pause
```
code:
```js
let proxy = "127.0.0.1"
var url = require('url');
let options = url.parse(proxy);
let agent = new HttpsProxyAgent(options);

const OJS = require("owop-js");
const Client = new OJS.Client({
    reconnect: true,
    controller: true,
    agent
});

Client.on("join", () => {
    Client.chat.send("Hello!");
});
```
sorry i so stupid xD

**Comment by MapleHackersoff** [comment]
@dimdenGD ?
